name: Deploy Backend to AWS

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'  

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          # In a real app, this would be 'pytest'
          echo "Running Unit Tests..."
          python -m compileall backend/  # This checks for syntax errors!

      - name: Generate Deployment Package
        run: |
          cd backend
          # The asterisk * usually skips hidden files, so we explicitly add .ebextensions
          zip -r ../deploy.zip . .ebextensions -x '*.git*' '*.DS_Store' 'venv/*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: eu-north-1                       
          application_name: Algo-Quant-backend     
          environment_name: algoquant-env          
          version_label: "ver-${{ github.sha }}"
          deployment_package: deploy.zip